### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by elliotchance**

### CODE REVIEW

**Comment by jszobody** [comment]
Would love to see this merged in (and registered on packagist)

**Comment by elliotchance** [comment]
What is the hold up guys? Is there anything your still unsure about?

**Comment by nfauchelle** [comment]
+1

**Comment by elliotchance** [comment]
Since xero is totally unwilling to fix up their code, or allow anyone else to, the new community package will be at: https://github.com/elliotchance/xero-api

**Comment by jszobody** [comment]
I'd prefer not to use a fork, personally. Since I can't be confident it will always be up to date. 

In my own project I now have this setup in composer.json:

    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "XeroAPI/XeroOAuth-PHP",
                "version": "dev-master",
                "source": {
                    "url": "https://github.com/XeroAPI/XeroOAuth-PHP",
                    "type": "git",
                    "reference": "origin/master"
                }
            }
        }
    ],
    "require": {
        "XeroAPI/XeroOAuth-PHP" : "dev-master"
    },
    "autoload": {
        "classmap": [
            "vendor/XeroAPI/XeroOAuth-PHP/lib"
        ]
    },

That seems to work well for me. Not ideal of course, but at least I'm pulling from the authoritative repo.

**Comment by elliotchance** [comment]
I'd like it to be the official package as well, but despite fighting for months, Xero is unwilling to budge. This make this package unreliable since we already have a bunch of people that have forked and added fixes to their forks. I will continue to pull in changes in from this repository of course, the composer file can be setup so that we do not need to move the files from where they are to prevent merge conflicts in the future.

**Comment by mhlavac** [comment]
Is there any reason why composer.json can't be added. This way when I search for xero api on packagist I get a lot of forks, but not the official implementation. Would it be more secure to have your own implementation there? It's few minutes change that would make everyone's life little bit easier.

image

**Pull request merged**
