### PR TITLE
Add composer support

### LINKED ISSUE #19: Should be available through composer.
This library should be available as a composer package.

### PR DESCRIPTION
**Pull request by lloydhazlett**
Resolves #19

### CODE REVIEW

**Comment by kylestev** [comment]
@billda :+1: I am leaning towards not supporting Xero in my product because of the development and ops overhead it would add. This is poor form.

**Comment by elliotchance** [comment]
This discustion is becoming a joke. It's hard to enough to get over the fact that quality of this
package is very poor - you lack any willingness to improve it, even if others have done the work for
you.

You have a wealth of developers that are happy to work to improve this package, this includes things
like adding composer support, fixing bugs and even adding new features. However, to receive that
support you have to give back. Please understand that engineers aren't going to trouble of improving
your software and putting in a pull request just to waste your time. They are fixing deficiencies
that benefit everyone using your software and your neglect and naivety is doing the opposite,
**hurting everyone**.

Once engineers lose faith in your software because your don't return that support, they will not
help you anymore. And it will turn into, well, this...

@barrywise has already said it's fine. So let's start improving?

**Comment by barrywise** [comment]
I changed my mind; I recently tried to work with a library on GitHub and couldn't even install it without installing Composer! It is now getting so bloated and corrupt it has to create it's own vendor and autoload file.  So I have changed my view that it was harmless, to being outright destructive.  

So personally, I hate Composer and will never use it or allow any devs that work for me to ever use it.  But go ahead and make a fork that uses it, because obviously there are plenty of people that do.  I have nothing to do with this project, but it seems quite a few of your users are crying out for Composer support.  As much as I hate it, if my users were asking for it, I'd support it.

**Comment by elliotchance** [comment]
@barrywise, let's take a step back and look at the bigger picture. **You should never commit code from a 3rd party to your own repository**; I shouldn't need to explain why this is. This applies to both you and everyone using the Xero package.

You should swap out the OAuth library in this package for one provided by a properly maintained package - hence you do not retain any 3rd party code. If bug were found in that related library they could be patched and your software would be inherently patched as well.

If "your developers" choose not use composer, what is the harm? They carry around an extra `composer.json` file since they are not loading it through composer. Everyone else, that is a real PHP engineer can use it properly.

**Comment by eugene1g** [comment]
@barrywise If one of the goals for this library is to allow developers to get started with the XERO api quickly (as is stated in the opening paragraph), then you have to leverage the currently-agreed mainstream method of distributing packages among your developers. Composer may not be a formal standard for PHP, but it is on the same level as NPM/Bower are for JavaScript. A lot of people do not like NPM/Bower, but that's irrelevant in the discussion of whether using those channels makes your library easier to use for a very broad range of developers.

Conceptually, not leveraging Composer for a PHP project is the same as not leveraging yum/apt for a Linux project. "I compile all my dependencies from source, and so should you" is not a broadly applicable justification.

**Comment by barrywise** [comment]
As I said before, I have nothing to do with this project, and can't speak for or against the use of Composer within it.  I don't like Composer, but my opinion means nothing, and shouldn't stop you or the devs that run this code from applying it.  

So by all means, use Composer, I have nothing to do with this.

**Comment by ronanq** [comment]
To be reviewed shortly

**Comment by TomasVotruba** [comment]
:+1: I'd recommend to use/to check some PHP framework/components, e.g. Symfony, Laravel, Nette, Doctrine.... There it's much more obvious the purpose of this single file.

Also [Github trending libs](https://github.com/trending?l=php) might be good source of trends in PHP libs.

**Comment by TomasVotruba** [comment]
Thank you @ronanq

**Comment by elliotchance** [comment]
Yay! Is this registered on packagist yet? I'll delete my fork when that's done.

**Comment by cbakker** [comment]
It is on Packagist: https://packagist.org/packages/xero/xerooauth-php

@ronanq Great move! Thank you. Now you are available on Packagist, it would be really helpful to register new versions in Github, with normal Git tags or with their release feature: https://github.com/XeroAPI/XeroOAuth-PHP/releases

That way it is easy for people to require a specific version of this library, and you will be able to make breaking changes more easily.

**Comment by elliotchance** [comment]
@cbakker might have already beat you on this one :stuck_out_tongue: 

https://github.com/XeroAPI/XeroOAuth-PHP/issues/39

**Comment by cbakker** [comment]
Haha, in that case: I second #39 :+1:

**Pull request merged**
